### ISSUE TITLE
Error creating Forms (Ios/Android)

### ISSUE THREAD

**Issue by GuilhermeMorais** [picolyl/XamarinFormsTemplates#1]
Hi!
   I just update my Xamarin to 4.1.2.18 (fcbe082), I was trying to create a new project using yours templates and I got a few errors, may these could help you to correct the problem:
 I just retried 2 more times and got the excatly same errors.

> Package Installation Error
> 
> Could not add all required packages to the project. The following packages failed to install from 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\XAMARIN\XAMARIN\4.1.2.18\Packages':
> 
> Xamarin.Forms.2.0.0.6482 : Failed to add reference to 'Xamarin.Forms.Core'.

_then_

> Xamarin.Forms.2.0.0.6482 : Failed to add reference to 'FormsViewGroup'.
> Xamarin.Android.Support.v4.23.0.1.3 : Failed to add reference to 'Xamarin.Android.Support.v4'.
> Xamarin.Android.Support.Design.23.0.1.3 : Failed to add reference to Xamarin.Android.Support.Design'.
> Xamarin.Android.Support.v7.AppCompat.23.0.1.3 : Failed to add reference to Xamarin.Android.Support.v7.AppCompat'.
> Xamarin.Android.Support.v7.CardView.23.0.1.3 : Failed to add reference to Xamarin.Android.Support.v7.CardView'.
> Xamarin.Android.Support.v7.MediaRouter.23.0.1.3 : Failed to add reference to 'Xamarin.Android.Support.v7.MediaRouter'.

_last_

> A problem was encountered creating the sub project 'DataBinding.iOS'.  An equivalent project (a project with the same global properties and tools version) is already present in the project collection, with the path "C:\Projetos\XamarinProjects\DataBinding\DataBinding\DataBinding.iOS\DataBinding.iOS.csproj". To load an equivalent into this project collection, unload this project first.

**Comment by GuilhermeMorais** [comment]
Sorry, this problem starts to occurs in VS2015 (Update3) with the last version of Xamarin (4.1.2.18) in the default templates.

**Comment by BatistaGabriel** [comment]
Hi, I'm also having the same problem here. How can I find a solution for it? Thanks
